# Generated by Django 5.0.1 on 2024-02-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BMI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmi_value", models.FloatField(unique=True, verbose_name="BMI Value")),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            (0.0, "Invalid BMI"),
                            (18.4, "Underweight"),
                            (24.9, "Normal weight (Healthy)"),
                            (29.9, "Overweight"),
                            (34.9, "Obesity (Class 1)"),
                            (39.9, "Obesity (Class 2)"),
                            (float("inf"), "Obesity (Class 3) or Severe Obesity"),
                        ],
                        default=0.0,
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(default="Full Name", max_length=255, unique=True),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
