# Generated by Django 5.0.1 on 2024-02-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_userlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlist",
            name="bmi",
            field=models.ManyToManyField(related_name="userlists", to="api.bmi"),
        ),
        migrations.AddField(
            model_name="userlist",
            name="height",
            field=models.FloatField(default=0.0, verbose_name="Height (meters)"),
        ),
        migrations.AddField(
            model_name="userlist",
            name="weight",
            field=models.FloatField(default=0.0, verbose_name="Weight (kgs)"),
        ),
    ]
