# Generated by Django 5.0.1 on 2024-02-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_userlist_bmi_userlist_height_userlist_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmi",
            name="users",
            field=models.ManyToManyField(related_name="bmi_values", to="api.userlist"),
        ),
        migrations.AlterField(
            model_name="bmi",
            name="classification",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
