# Generated by Django 5.0.1 on 2024-02-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_bmi_users_alter_bmi_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlist",
            name="bmi",
            field=models.ManyToManyField(
                blank=True, related_name="userlists", to="api.bmi"
            ),
        ),
    ]
